// src/anonymous-chat/schemas/anonymous-message.schema.ts
import { Prop, Schema, SchemaFactory } from '@nestjs/mongoose';
import { Document, Types } from 'mongoose';

export enum AnonymousMessageType {
  TEXT = 'text',
  SYSTEM = 'system', // e.g., "User joined", "User left"
}

@Schema({ timestamps: true })
export class AnonymousMessage extends Document {
  @Prop({ type: String, required: true, index: true })
  roomId: string; // Reference to AnonymousRoom.roomId

  // ===== SENDER INFO =====
  @Prop({ type: Types.ObjectId, ref: 'User', required: true })
  senderId: Types.ObjectId; // Real user ID (hidden from partner)

  @Prop({ type: String, required: true })
  senderAnonymousName: string; // Display name (e.g., "Blue Panda")

  // ===== MESSAGE CONTENT =====
  @Prop({
    type: String,
    enum: AnonymousMessageType,
    default: AnonymousMessageType.TEXT,
  })
  type: AnonymousMessageType;

  @Prop({ type: String, required: true })
  content: string;

  // ===== METADATA =====
  @Prop({ type: Boolean, default: false })
  isDeleted: boolean;

  @Prop({ type: Date })
  deletedAt?: Date;

  @Prop({ type: Types.ObjectId, ref: 'User' })
  deletedBy?: Types.ObjectId;

  // ===== TIMESTAMPS (auto-generated by Mongoose) =====
  createdAt?: Date;
  updatedAt?: Date;
}

export const AnonymousMessageSchema =
  SchemaFactory.createForClass(AnonymousMessage);

// ===== INDEXES =====
AnonymousMessageSchema.index({ roomId: 1, createdAt: -1 }); // For retrieving messages
AnonymousMessageSchema.index({ roomId: 1, isDeleted: 1 });
AnonymousMessageSchema.index({ senderId: 1 }); // For user history (optional)
