// src/matching/compatibility.service.ts
import { Injectable } from '@nestjs/common';
import { StarSign } from 'src/common/enums';

@Injectable()
export class CompatibilityService {
  // === NUMEROLOGY MATRIX (1-9) ===
  private numerologyCompat: Record<number, Record<number, number>> = {
    1: { 1: 7, 2: 6, 3: 9, 4: 8, 5: 10, 6: 5, 7: 4, 8: 3, 9: 2 },
    2: { 1: 6, 2: 8, 3: 5, 4: 9, 5: 4, 6: 10, 7: 3, 8: 9, 9: 6 },
    3: { 1: 9, 2: 5, 3: 7, 4: 4, 5: 10, 6: 6, 7: 5, 8: 2, 9: 9 },
    4: { 1: 8, 2: 9, 3: 4, 4: 6, 5: 3, 6: 10, 7: 9, 8: 5, 9: 4 },
    5: { 1: 10, 2: 4, 3: 10, 4: 3, 5: 7, 6: 5, 7: 8, 8: 2, 9: 3 },
    6: { 1: 5, 2: 10, 3: 6, 4: 10, 5: 5, 6: 8, 7: 4, 8: 10, 9: 9 },
    7: { 1: 4, 2: 3, 3: 5, 4: 9, 5: 8, 6: 4, 7: 7, 8: 3, 9: 5 },
    8: { 1: 3, 2: 9, 3: 2, 4: 5, 5: 2, 6: 10, 7: 3, 8: 6, 9: 2 },
    9: { 1: 2, 2: 6, 3: 9, 4: 4, 5: 3, 6: 9, 7: 5, 8: 2, 9: 7 },
  };

  // === ZODIAC COMPATIBILITY MATRIX (1-10) ===
  private zodiacCompat: Record<StarSign, Record<StarSign, number>> = {
    [StarSign.Aries]: {
      [StarSign.Aries]: 8,
      [StarSign.Taurus]: 4,
      [StarSign.Gemini]: 9,
      [StarSign.Cancer]: 3,
      [StarSign.Leo]: 10,
      [StarSign.Virgo]: 5,
      [StarSign.Libra]: 9,
      [StarSign.Scorpio]: 6,
      [StarSign.Sagittarius]: 10,
      [StarSign.Capricorn]: 4,
      [StarSign.Aquarius]: 9,
      [StarSign.Pisces]: 7,
    },
    [StarSign.Taurus]: {
      [StarSign.Aries]: 4,
      [StarSign.Taurus]: 8,
      [StarSign.Gemini]: 5,
      [StarSign.Cancer]: 9,
      [StarSign.Leo]: 6,
      [StarSign.Virgo]: 10,
      [StarSign.Libra]: 7,
      [StarSign.Scorpio]: 8,
      [StarSign.Sagittarius]: 3,
      [StarSign.Capricorn]: 10,
      [StarSign.Aquarius]: 5,
      [StarSign.Pisces]: 9,
    },
    [StarSign.Gemini]: {
      [StarSign.Aries]: 9,
      [StarSign.Taurus]: 5,
      [StarSign.Gemini]: 8,
      [StarSign.Cancer]: 4,
      [StarSign.Leo]: 9,
      [StarSign.Virgo]: 6,
      [StarSign.Libra]: 10,
      [StarSign.Scorpio]: 5,
      [StarSign.Sagittarius]: 9,
      [StarSign.Capricorn]: 3,
      [StarSign.Aquarius]: 10,
      [StarSign.Pisces]: 7,
    },
    [StarSign.Cancer]: {
      [StarSign.Aries]: 3,
      [StarSign.Taurus]: 9,
      [StarSign.Gemini]: 4,
      [StarSign.Cancer]: 8,
      [StarSign.Leo]: 5,
      [StarSign.Virgo]: 7,
      [StarSign.Libra]: 6,
      [StarSign.Scorpio]: 10,
      [StarSign.Sagittarius]: 4,
      [StarSign.Capricorn]: 7,
      [StarSign.Aquarius]: 3,
      [StarSign.Pisces]: 10,
    },
    [StarSign.Leo]: {
      [StarSign.Aries]: 10,
      [StarSign.Taurus]: 6,
      [StarSign.Gemini]: 9,
      [StarSign.Cancer]: 5,
      [StarSign.Leo]: 8,
      [StarSign.Virgo]: 4,
      [StarSign.Libra]: 10,
      [StarSign.Scorpio]: 7,
      [StarSign.Sagittarius]: 10,
      [StarSign.Capricorn]: 3,
      [StarSign.Aquarius]: 8,
      [StarSign.Pisces]: 6,
    },
    [StarSign.Virgo]: {
      [StarSign.Aries]: 5,
      [StarSign.Taurus]: 10,
      [StarSign.Gemini]: 6,
      [StarSign.Cancer]: 7,
      [StarSign.Leo]: 4,
      [StarSign.Virgo]: 8,
      [StarSign.Libra]: 7,
      [StarSign.Scorpio]: 9,
      [StarSign.Sagittarius]: 3,
      [StarSign.Capricorn]: 10,
      [StarSign.Aquarius]: 5,
      [StarSign.Pisces]: 8,
    },
    [StarSign.Libra]: {
      [StarSign.Aries]: 9,
      [StarSign.Taurus]: 7,
      [StarSign.Gemini]: 10,
      [StarSign.Cancer]: 6,
      [StarSign.Leo]: 10,
      [StarSign.Virgo]: 7,
      [StarSign.Libra]: 8,
      [StarSign.Scorpio]: 6,
      [StarSign.Sagittarius]: 9,
      [StarSign.Capricorn]: 5,
      [StarSign.Aquarius]: 10,
      [StarSign.Pisces]: 7,
    },
    [StarSign.Scorpio]: {
      [StarSign.Aries]: 6,
      [StarSign.Taurus]: 8,
      [StarSign.Gemini]: 5,
      [StarSign.Cancer]: 10,
      [StarSign.Leo]: 7,
      [StarSign.Virgo]: 9,
      [StarSign.Libra]: 6,
      [StarSign.Scorpio]: 8,
      [StarSign.Sagittarius]: 5,
      [StarSign.Capricorn]: 9,
      [StarSign.Aquarius]: 4,
      [StarSign.Pisces]: 10,
    },
    [StarSign.Sagittarius]: {
      [StarSign.Aries]: 10,
      [StarSign.Taurus]: 3,
      [StarSign.Gemini]: 9,
      [StarSign.Cancer]: 4,
      [StarSign.Leo]: 10,
      [StarSign.Virgo]: 3,
      [StarSign.Libra]: 9,
      [StarSign.Scorpio]: 5,
      [StarSign.Sagittarius]: 8,
      [StarSign.Capricorn]: 4,
      [StarSign.Aquarius]: 10,
      [StarSign.Pisces]: 7,
    },
    [StarSign.Capricorn]: {
      [StarSign.Aries]: 4,
      [StarSign.Taurus]: 10,
      [StarSign.Gemini]: 3,
      [StarSign.Cancer]: 7,
      [StarSign.Leo]: 3,
      [StarSign.Virgo]: 10,
      [StarSign.Libra]: 5,
      [StarSign.Scorpio]: 9,
      [StarSign.Sagittarius]: 4,
      [StarSign.Capricorn]: 8,
      [StarSign.Aquarius]: 6,
      [StarSign.Pisces]: 8,
    },
    [StarSign.Aquarius]: {
      [StarSign.Aries]: 9,
      [StarSign.Taurus]: 5,
      [StarSign.Gemini]: 10,
      [StarSign.Cancer]: 3,
      [StarSign.Leo]: 8,
      [StarSign.Virgo]: 5,
      [StarSign.Libra]: 10,
      [StarSign.Scorpio]: 4,
      [StarSign.Sagittarius]: 10,
      [StarSign.Capricorn]: 6,
      [StarSign.Aquarius]: 8,
      [StarSign.Pisces]: 7,
    },
    [StarSign.Pisces]: {
      [StarSign.Aries]: 7,
      [StarSign.Taurus]: 9,
      [StarSign.Gemini]: 7,
      [StarSign.Cancer]: 10,
      [StarSign.Leo]: 6,
      [StarSign.Virgo]: 8,
      [StarSign.Libra]: 7,
      [StarSign.Scorpio]: 10,
      [StarSign.Sagittarius]: 7,
      [StarSign.Capricorn]: 8,
      [StarSign.Aquarius]: 7,
      [StarSign.Pisces]: 8,
    },
  };

  getNumerologyScore(num1: number, num2: number): number {
    if (!num1 || !num2) return 5;
    return this.numerologyCompat[num1]?.[num2] ?? 5;
  }

  getZodiacScore(sign1: StarSign, sign2: StarSign): number {
    if (!sign1 || !sign2) return 5;
    return this.zodiacCompat[sign1]?.[sign2] ?? 5;
  }
}
